finserv/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from reg_sign_in_out import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('', include('reg_sign_in_out.urls')),
    path('', include('portfolio.urls')),

    path('logout/',views.user_logout,name='logout'),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='password_reset.html'),name='reset_password'), #, email_template_name='email_template.html'
    path('password-reset/sent/',auth_views.PasswordResetDoneView.as_view(template_name='password_reset_sent.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html',success_url = reverse_lazy('reg_sign_in_out:user_login')),name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html',),name='password_reset_complete'),

]

portfolio/urls.py
from django.urls import path
from . import views
from finserv import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = "portfolio"

urlpatterns = [
                path('addport/',views.addport,name='addport'),
                path('portDetails/<str:portName>/',views.portdetails,name='portdetails'),
                path('sellPortfolio/<str:portName>/',views.sellPortfolio,name='sellPortfolio'),
                path('rebalance/<str:portName>/',views.rebalance,name='rebalance'),
                path('sellAsset/<str:portName>+<str:assetName>/',views.sellAsset,name='sellAsset'),
            ]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

portfolio/models.py
from django.db import models

from django.contrib.auth.models import User
from django.db.models.base import ModelState
import datetime
from django.utils.timezone import now

class Portfolio(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    uPortName = models.CharField(max_length=64,primary_key=True)
    # uPortName2 = models.CharField(max_length=64)
    created_on = models.DateTimeField(auto_now_add=True)
    sold = models.BooleanField(default=False)
    sold_on = models.DateTimeField(null=True)
    realized_profit = models.FloatField(default=0)
    
    # def save(self):
    #     self.created_on = datetime.datetime.now()
    #     super(Portfolio, self).save()

    def __str__(self):
        return self.user.username+"-"+self.uPortName

# 
class Assets(models.Model):
    assetName = models.CharField(max_length=64,primary_key=True)
    assetTicker = models.CharField(max_length=8)

    def __str__(self):
        return self.assetName+"-"+self.assetTicker

class AssetPriceMovements(models.Model):
    ticker = models.ForeignKey(Assets,on_delete=models.CASCADE)
    adj_close = models.FloatField()
    date = models.DateTimeField()
    def __str__(self):
        return self.ticker.assetName+"  "+str(round(self.adj_close,3))+" "+self.date.strftime('%Y-%m-%d')

    class Meta:
        unique_together = ('ticker', 'date',)






class PortfolioAssets(models.Model):
    sold = models.BooleanField(default=False)
    port = models.ForeignKey(Portfolio, on_delete=models.CASCADE)
    asset = models.ForeignKey(Assets, on_delete=models.CASCADE)
    assetQuantity = models.FloatField()
    usdSpent = models.FloatField()
    bought_on = models.DateTimeField(auto_now_add=True)
    sold_on = models.DateTimeField(null=True)
    sold_for_usd = models.FloatField(null=True)
    
    # def save(self):
    #     self.bought_on = datetime.datetime.now()
    #     super(PortfolioAssets, self).save()

    def __str__(self):
        return self.port.user.username+"-"+self.port.uPortName+"-"+self.asset.assetName+" "+self.bought_on.strftime('%Y-%m-%d')+" "+str(self.sold)

portfolio/views.py
from datetime import datetime, timedelta
from django.shortcuts import render
from django.utils import timezone
from django.views.decorators import csrf
from riskfolio.Portfolio import Portfolio
from scipy import cluster
from scipy.cluster.hierarchy import dendrogram
from portfolio import models as pModels
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

from finserv.startup import ALL_ASSETS,ALL_ASSETS_REV, VALUE

from modules.helper import getLinePlot,calcPortfolioGain,gainChartUnrealizedProfitPortfolio,getPortPie,getDateWiseLinePlot
from modules import portfolio_opt

from pprint import pprint



def sellPortfolio(request,portName):

    assetObjectist = pModels.PortfolioAssets.objects.filter(port_id=portName,sold=False)
    
    portObj = pModels.Portfolio.objects.get(uPortName=portName)
    portObj.sold = True
    portObj.sold_on = timezone.now()
    realized_profit = 0

    for asset in assetObjectist:
        if asset.sold==False:
            asset.sold = True
            asset.sold_on = timezone.now()
            asset.sold_for_usd = pModels.AssetPriceMovements.objects.filter(ticker=asset.asset).latest('date').adj_close * asset.assetQuantity
            asset.save()
            realized_profit += asset.sold_for_usd - asset.usdSpent


    portObj.realized_profit += realized_profit
    portObj.save()

    return HttpResponseRedirect(reverse('dashboard:dash'))


    #<a class='col-lg-2 col-md-2 btn btn-success' href="{% url 'portfolio:sellPortfolio' port.id %}">Sell</a>

def sellAsset(request,portName,assetName):

    _sellAsset(portName,assetName,True)

    return HttpResponseRedirect(reverse('portfolio:portdetails',args=[portName]))  

def _sellAsset(portName,assetName,realized):

    asset = pModels.PortfolioAssets.objects.get(port__uPortName=portName,asset__assetName=assetName,sold=False)
    asset.sold = True
    asset.sold_on = datetime.now()
    asset.sold_for_usd = pModels.AssetPriceMovements.objects.filter(ticker__assetName=assetName).latest('date').adj_close * asset.assetQuantity
    asset.save()

    portObj = pModels.Portfolio.objects.get(uPortName=portName)
    portObj.realized_profit += asset.sold_for_usd - asset.usdSpent
    portObj.save()


def addAssetToPort(portObj,assetName,USD):
    print("Adding",assetName)
    assetObj = pModels.Assets.objects.get(assetName=assetName)
    cPrice = pModels.AssetPriceMovements.objects.filter(ticker=assetObj).latest('date').adj_close
    amtAssetOwned = USD/cPrice
    portAsset = pModels.PortfolioAssets.objects.create(port=portObj,asset=assetObj,assetQuantity=amtAssetOwned,usdSpent=USD,bought_on=datetime.now())
    portAsset.save()

@csrf_exempt
def addport(request):

    if request.user.is_authenticated==False:
        return HttpResponseRedirect(reverse('reg_sign_in_out:user_login'))  

    if request.method == "POST":

        opt = True if 'opt' in request.POST else False
        letOptPick = True if 'ap' in request.POST else False

        portName = request.POST.get('portName')
        create_port = pModels.Portfolio.objects.create(user=request.user,uPortName=portName,created_on=datetime.now())
        create_port.save()

        grandAmount = float(request.POST.get('amount'))
        
        if opt==False:
            assets = {}
            for i in range(100):
                assetName = request.POST.get('assetName'+str(i))
                
                amount = request.POST.get('assetAmount'+str(i))
                if assetName!=None:
                    assetName = " ".join(assetName.split("_"))
                    assets[assetName] = assets.get(assetName,0)+float(amount)
            for asset, amount in assets.items():
                addAssetToPort(create_port,asset,amount)


        elif opt==True and letOptPick==False:
            assets = []
            for i in range(100):
                assetName = request.POST.get('assetName'+str(i))
                
                if assetName!=None:
                    assetName = " ".join(assetName.split("_"))
                    assets.append(ALL_ASSETS[assetName])

            assets = list(set(assets))
            
            po = portfolio_opt.PortfolioOptmizer(tickList=assets)
            po.getWeights()
            weights = po.wCleaned

            for asset,weight in weights.items():
                print(asset,weight)
                addAssetToPort(create_port,ALL_ASSETS_REV[asset],weight*grandAmount)

        else:
            
            assets = list(ALL_ASSETS.values())
            po = portfolio_opt.PortfolioOptmizer(tickList=assets)
            po.getWeights()
            weights = po.wCleaned

            for asset,weight in weights.items():
                addAssetToPort(create_port,ALL_ASSETS_REV[asset],weight*grandAmount)


        return HttpResponseRedirect(reverse('dashboard:dash'))

    return render(request, 'portfolio/addport.html',context={'assetList':VALUE})










def rebalance(request,portName):

    assetObjectist = pModels.PortfolioAssets.objects.filter(port__uPortName=portName,sold=False)
    totalAmount = 0
    netWorth = 0
    assetList = []

    for asset in assetObjectist:
        if asset.sold==False:
            totalAmount += asset.usdSpent
            netWorth += pModels.AssetPriceMovements.objects.filter(ticker=asset.asset).latest('date').adj_close * asset.assetQuantity
            assetList.append(asset.asset.assetTicker)
            _sellAsset(portName,asset.asset.assetName,False)
    print("LIst",assetList)

    po = portfolio_opt.PortfolioOptmizer(tickList=assetList)
    po.getWeights()
    weights = po.wCleaned
    print(weights)
    portObj = pModels.Portfolio.objects.get(uPortName=portName)

    for asset,weight in weights.items():
        addAssetToPort(portObj,ALL_ASSETS_REV[asset],weight*netWorth)



    return HttpResponseRedirect(reverse('portfolio:portdetails',args=[portName]))  


@csrf_exempt
def portdetails(request,portName):
    
    portObj = pModels.Portfolio.objects.get(uPortName=portName)

    if request.user.is_authenticated==False:
        return HttpResponseRedirect(reverse('reg_sign_in_out:user_login'))  

    if request.method == "POST":
        assetName = " ".join(request.POST.get('assetName').split("_"))
        print(assetName)
        amount = float(request.POST.get('amount'))
        addAssetToPort(portObj,assetName,amount)
        return HttpResponseRedirect(reverse('portfolio:portdetails',args=[portName]))  

    
    assetList = pModels.PortfolioAssets.objects.filter(port=portObj)
    indLinePlot = {}

    for pAsset in assetList:
        line,dateArr = getLinePlot(pAsset.asset.assetName)
        indLinePlot[pAsset.asset.assetName] = line
    
    
    dateArr = [cdate.strftime("%d/%m/%Y") for cdate in dateArr]

    total_asset_dict,gains_dict,totalCurrProfit,totalCurrWorth = calcPortfolioGain(portObj)

    portPie = getPortPie(portObj)

    cum_line_dict = getDateWiseLinePlot(portObj)


    port_opt_obj = portfolio_opt.PortfolioOptmizer(tickList=[ALL_ASSETS[ass] for ass in indLinePlot.keys()])

    assetListabc = []
    weightabc = []
    for asset,weight in portPie.items():
        assetListabc.append(ALL_ASSETS[asset])
        weightabc.append(weight/100)


    port_opt_obj.setWeigth(assetListabc,weightabc)

    frontier = port_opt_obj.frontierPlotPlotly()
    frontierArea = port_opt_obj.frontierAreaPlot()
    # cluster = port_opt_obj.clusterPlot()
    # dendrogram = port_opt_obj.dendrogramPlot()
    

    return render(request, 'portfolio/portdetails.html',context={
        'cum_line':cum_line_dict,
        'portPie':portPie,
        'curProfit':totalCurrProfit,
        'curWorth':totalCurrWorth,
        'gainDict':gains_dict,
        'allAssets': total_asset_dict,
        'portName':portObj.uPortName,
        'dateArr':dateArr,
        'indLine':indLinePlot,
        'frontier':frontier,
        'frontierArea':frontierArea,
        'portObj':portObj,
        'assetList':VALUE,
    })

templates/portfolio/addport.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html lang="en">
{% load static %}

{% block body_block %}
{% csrf_token %}
<div class="container-scroller">
    {% csrf_token %}
    <div class="container-fluid page-body-wrapper">
        <div class="row w-100 mx-0 col-lg-4 mx-auto">
            <div class="content-wrapper">
                <div class="row  auth-form-light text-left py-5 px-4 px-sm-5">
                    <div class="col-md-8 grid-margin stretch-card" style="margin:0 auto;">
                        <div class="card">
                            {% csrf_token %}
                            <form action="{% url 'portfolio:addport'%}" method="post">
                                {% csrf_token %}
                                <div class="card-body" id="holder">
                                    <h4 class="card-title">Add Portfolio</h4>
                                    <p class="card-description">
                                        Portfolio Details
                                    </p>
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text">Portfolio Name</span>
                                            </div>
                                            {% csrf_token %}
                                            <input type="text" class="form-control" name="portName"
                                                placeholder="Enter Portfolio Name" aria-label="portName" required>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text bg-primary text-white">Total
                                                    Amount*</span>
                                            </div>
                                            {% csrf_token %}
                                            <input type="number" min="1" name="amount" class="form-control"
                                                aria-label="Amount (to the nearest dollar)" required>
                                            <div class="input-group-append">
                                                <span class="input-group-text">$</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div>
                                        <div>
                                            <input type="checkbox" id="opt" name="opt" onclick="algopic()">
                                            <label for="scales">Use Optimizer</label>
                                        </div>

                                        <input type="checkbox" id="ap" name="ap" onclick="remAssetCard()">
                                        <label for="scales">Let The Algorith Pick Assets</label>
                                      </div>
                                      

                                    <div class="col-12 grid-margin stretch-card">
                                        <div class="card" id='cardHolder'>

                                        </div>

                                    </div>
                                    <input id="clickMe" type="button" value="Add Asset" onclick="replicate();" />

                                </div>
                                <div style="padding-left:30px; padding-bottom: 30px;">
                                    <button class="btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn"
                                        type="submit">Create</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="/static/dashboard/vendors/js/vendor.bundle.base.js"></script>

<script src="/static/dashboard/vendors/typeahead.js/typeahead.bundle.min.js"></script>
<script src="/static/dashboard/vendors/select2/select2.min.js"></script>
<script src="/static/dashboard/vendors/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>

<script src="/static/dashboard/js/off-canvas.js"></script>
<script src="/static/dashboard/js/hoverable-collapse.js"></script>
<script src="/static/dashboard/js/template.js"></script>
<script src="/static/dashboard/js/settings.js"></script>
<script src="/static/dashboard/js/todolist.js"></script>

<script src="/static/dashboard/js/file-upload.js"></script>
<script src="/static/dashboard/js/typeahead.js"></script>
<script src="/static/dashboard/js/select2.js"></script>


<template id='assetCardTemp'>
    <div class="card-body" id='assetCard'>
        <h4 class="card-title">Asset</h4>

        <label class="sr-only" for="inlineFormInputName2">Asset</label>
        {% csrf_token %}
        <input type="text" class="form-control mb-2 mr-sm-2" id='assetNamexx' name='assetNamexxx'
            placeholder="Asset Name" hidden>

        <select type="text" class="form-control mb-2 mr-sm-2" id='assetName' name='assetName'>
            {% for assetval,asset in assetList.items %}
                <option value={{assetval}}>{{asset}}</option>
            {% endfor %}
        </select>



        <div class="divAmt" style="visibility: visible;">
            <label class="sr-only" for="inlineFormInputGroupUsername2">Amount</label>
            <div class="input-group mb-2 mr-sm-2" id="divAmt" >
                <div class="input-group-prepend">
                    <div class="input-group-text">$</div>
                </div>
                {% csrf_token %}
                <input type="text" class="form-control" id='assetAmount' name='assetAmount'
                    placeholder="Amount">
            </div>
        </div>
        <div class="form-check mx-sm-2">
            <input id="clickMe" type="button" value="Remove" onclick="del(this);" />
        </div>

    </div>
</template>




<script>
    var child = document.getElementById("assetCardTemp");
    var father = document.getElementById('cardHolder');

    var rep = 0;

    function replicate() {
        var checkBox = document.getElementById("ap");
        if (checkBox.checked == true){
            return;
        }
        console.log("Adding: "+rep)
        var cclone = child.content.cloneNode(true)
        cclone.getElementById('assetCard').id = 'assetCard' + rep
        cclone.querySelector("select[name='assetName']").name = 'assetName' + rep
        cclone.querySelector("input[name='assetAmount']").name = 'assetAmount' + rep

        rep += 1
        father.appendChild(cclone)
    };
    function del(buttonEle) {
        console.log(buttonEle);
        var cardxyzlower = buttonEle.parentNode.parentNode;
        var cardxyzhigher = cardxyzlower.parentNode;
        cardxyzhigher.removeChild(cardxyzlower);
    };

    function remAssetCard() {
        var checkBox = document.getElementById("ap");
        if (checkBox.checked == true){
            document.getElementById("opt").checked = true;
            for(var i=0;i<rep;i++){
                try{
                    var but = document.querySelector("div[id='assetCard"+i+"']")
                    console.log(but);
                    console.log("div[id='assetCard"+i+"']");
                    father.removeChild(but);
                }
                catch(err){
                    
                }
            }
        }
    };

    function algopic() {
        var checkBox = document.getElementById("opt");
        var x = document.getElementById('holder');
        console.log(x);
        x = x.getElementsByClassName("divAmt");
        if(checkBox.checked){
            
            for(var i=0;i<x.length ;i++){
                    x[i].style.visibility = "hidden";
            }
        }
        else{
            for(var i=0;i<x.length;i++){
                x[i].style.visibility = "visible";
            }
        }
    };


</script>

{% endblock body_block %}