finserv/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from reg_sign_in_out import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('', include('reg_sign_in_out.urls')),
    path('', include('portfolio.urls')),

    path('logout/',views.user_logout,name='logout'),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='password_reset.html'),name='reset_password'), #, email_template_name='email_template.html'
    path('password-reset/sent/',auth_views.PasswordResetDoneView.as_view(template_name='password_reset_sent.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html',success_url = reverse_lazy('reg_sign_in_out:user_login')),name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html',),name='password_reset_complete'),

]

reg_sign_in_out/urls.py
from django.urls import path
from . import views

app_name = "reg_sign_in_out"

urlpatterns = [
    path('user_login/',views.user_login,name='user_login'),
    path('registration/',views.registration,name="registration"),

]

reg_sign_in_out/models.py
from django.db import models
from django.contrib.auth.models import User



class Registration(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)
    phone_number = models.CharField(blank=False,max_length=10)
    
    def __str__(self):
        return self.user.username
    

reg_sign_in_out/forms.py
from django import forms
from reg_sign_in_out.models import *
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    first_name = forms.CharField(max_length=30,required=True,
                                widget = forms.TextInput(attrs={'class': 'input'}))
    last_name = forms.CharField(max_length=30,required=True,
                                widget = forms.TextInput(attrs={'class': 'input'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input'}),)
    
    username = forms.CharField(max_length=30,required=True,
                                widget = forms.TextInput(attrs={'class': 'input'}))
    email = forms.CharField(max_length=30,required=True,
                                widget = forms.TextInput(attrs={'class': 'input'}))
    class Meta:
        model = User
        fields = ('first_name','last_name','username','email','password',)

    def clean_username(self):
        username = self.cleaned_data['username']

        if User.objects.exclude(pk=self.instance.pk).filter(username=username).exists():
            raise forms.ValidationError('Exists')
        return username


class RegistrationForm(forms.ModelForm):
    
    class Meta:
        model = Registration
        fields = ('phone_number',)

reg_sign_in_out/views.py
from django.shortcuts import render
from reg_sign_in_out.models import *
from . import forms 
import requests
import urllib.parse
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_protect
import json
import os
from finserv.settings import STATIC_DIR
import re


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('reg_sign_in_out:user_login'))  

@csrf_protect
def registration(request):

    registered = False

    if request.method == "POST":
        form = forms.UserForm(request.POST)
        profileform = forms.RegistrationForm(request.POST)

        if form.is_valid() and profileform.is_valid():


            user = form.save()
            user.set_password(user.password)
            user.save()

            profile = profileform.save(commit=False)
            profile.user = user

            profile.save()

            registered = True
            return HttpResponseRedirect(reverse('reg_sign_in_out:user_login'))
        
        else:

            print(form.errors,profileform.errors)
            
            return render(request,"reg_sign_in_out/registration.html",{"tried":"True",
                                                    "registered":registered,
                                                   "profile_form":profileform,
                                                   "user_form":form,
                                                   "errorone":form.errors,
                                                   "errortow":profileform.errors,
                                                   })
            

    else:
        user = forms.UserForm()
        profileform = forms.RegistrationForm()

    return render(request,"reg_sign_in_out/registration.html",{"registered":registered,
                                                   "profile_form":profileform,
                                                   "user_form":user,
                                                   })


@csrf_protect
def user_login(request):

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        if request.POST.get('rememberme'):
            print("Remembering")
            request.session.set_expiry(1209600)
        else:
            print("Not rem")
        user = authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('dashboard:dash'))

        else:

            return render(request,"reg_sign_in_out/login.html",{'tried':1})

    else:
        return render(request,"reg_sign_in_out/login.html")

templates/reg_sign_in_out/login.html
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>FinServ </title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="/static/dashboard/vendors/feather/feather.css">
  <link rel="stylesheet" href="/static/dashboard/vendors/mdi/css/materialdesignicons.min.css">
  <link rel="stylesheet" href="/static/dashboard/vendors/ti-icons/css/themify-icons.css">
  <link rel="stylesheet" href="/static/dashboard/vendors/typicons/typicons.css">
  <link rel="stylesheet" href="/static/dashboard/vendors/simple-line-icons/css/simple-line-icons.css">
  <link rel="stylesheet" href="/static/dashboard/vendors/css/vendor.bundle.base.css">
  <!-- endinject -->
  <!-- Plugin css for this page -->
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="/static/dashboard/css/vertical-layout-light/style.css">
  <!-- endinject -->
  <link rel="shortcut icon" href="/static/dashboard/images/favicon.png" />
</head>

<body>
  <div class="container-scroller">
    <div class="container-fluid page-body-wrapper full-page-wrapper">
      <div class="content-wrapper d-flex align-items-center auth px-0">
        <div class="row w-100 mx-0">
          <div class="col-lg-4 mx-auto">
            <div class="auth-form-light text-left py-5 px-4 px-sm-5">
              <div class="brand-logo">
                <img src="/static/dashboard/images/logo.png" alt="logo">
              </div>
              <h4>Hello! let's get started</h4>
              <h6 class="fw-light">Sign in to continue.</h6>
              {% csrf_token %}
              <form class="pt-3" action="{% url 'reg_sign_in_out:user_login'%}" method="post">
              {% csrf_token %}
                <div class="form-group">
                  <input type="text" class="form-control form-control-lg" id="exampleInputEmail1" type="text" name="username" id="username" placeholder="Username">
                </div>
                <div class="form-group">
                  <input type="password" class="form-control form-control-lg" id="exampleInputPassword1" type="password" name="password" id="inputPassword" placeholder="Password">
                </div>
                  <button class="btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn" type="submit">SIGN IN</button>
                <div class="my-2 d-flex justify-content-between align-items-center">
                  <div class="form-check">
                    <label class="form-check-label text-muted">
                      {% csrf_token %}
                      <input type="checkbox" class="form-check-input" name="rememberme" id="rememberme">
                      Keep me signed in
                    </label>
                  </div>
                  <a href="{% url 'reset_password' %}" type='submit' class="auth-link text-black">Forgot password?</a>
                </div>
                
              </form>
              <br>
              {% if tried%}
                <h4>Ohhh! guess you typed the wrong password, try again.</h4>
              {% endif %}
              <br>
              <div class="text-center mt-4 fw-light">
                Don't have an account? <a href="{% url 'reg_sign_in_out:registration' %}" class="text-primary">Create</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- content-wrapper ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>
  <!-- container-scroller -->
  <!-- plugins:js -->
  <script src="/static/dashboard/vendors/js/vendor.bundle.base.js"></script>
  <!-- endinject -->
  <!-- Plugin js for this page -->
  <script src="/static/dashboard/vendors/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
  <!-- End plugin js for this page -->
  <!-- inject:js -->
  <script src="/static/dashboard/js/off-canvas.js"></script>
  <script src="/static/dashboard/js/hoverable-collapse.js"></script>
  <script src="/static/dashboard/js/template.js"></script>
  <script src="/static/dashboard/js/settings.js"></script>
  <script src="/static/dashboard/js/todolist.js"></script>
  <!-- endinject -->
</body>

</html>

templates/reg_sign_in_out/logino.html
{% extends "base.html" %}

{% load static %}
{% block head_block %}
<style>
  #color{
    color: darkgrey; !important
  }
  body {
    text-align: center;
}
form {
    display: inline-block;
}
</style>
<!-- <link rel="stylesheet" type="text/css" href="{% static 'login/login.css'%}"> -->
{% endblock head_block %}

{% block body_block %}
    {% csrf_token %}
    <div align='center' class="center container" id='color'>
      <form action="{% url 'reg_sign_in_out:user_login'%}" class="form-signin text-center blockx form-group" method="post">
        {% csrf_token %}
        <h1 class="h3 mb-3 font-weight-normal" id="h11">Please Sign In</h1>

        <div class="row justify-content-center " >
          <label for="username"  id="btn-white">Username</label>
          <input type="text" name="username" id="username" class="formx input textinput textInput form-control form-control" placeholder="Username" required="" autofocus="">
        </div><br>

        <div class="row justify-content-center " >
        <label for="inputPassword"  id="btn-white">Password</label>
        <input type="password" name="password" id="inputPassword" class="formx input textinput textInput form-control form-control" placeholder="Password" required="">
        </div><br>
        {% if tried %}
        <h7 id='color' >*Enter valid credentials</h7> <br>
        {% endif %}      
        <button class='btn btn-outline-info' type='submit'><a href="{% url 'reset_password' %}">Forgot Password</a></button><br><br>
        
        <button class='text-center btn btn-light' type="submit">Sign In</button>
      </form>
    </div>
    <br><br><br><br>
    {% endblock body_block %}

templates/reg_sign_in_out/registration.html
{% load static %}
{% load crispy_forms_tags %}


<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>FinServ </title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="/static/dashboard/vendors/feather/feather.css">
  <link rel="stylesheet" href="/static/dashboard/vendors/mdi/css/materialdesignicons.min.css">
  <link rel="stylesheet" href="/static/dashboard/vendors/ti-icons/css/themify-icons.css">
  <link rel="stylesheet" href="/static/dashboard/vendors/typicons/typicons.css">
  <link rel="stylesheet" href="/static/dashboard/vendors/simple-line-icons/css/simple-line-icons.css">
  <link rel="stylesheet" href="/static/dashboard/vendors/css/vendor.bundle.base.css">
  <!-- endinject -->
  <!-- Plugin css for this page -->
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="/static/dashboard/css/vertical-layout-light/style.css">
  <!-- endinject -->
  <link rel="shortcut icon" href="/static/dashboard/images/favicon.png" />
</head>

<body>

  <div class="container-scroller">
    <div class="container-fluid page-body-wrapper full-page-wrapper">
      <div class="content-wrapper d-flex align-items-center auth px-0">
        <div class="row w-100 mx-0">
          <div class="col-lg-4 mx-auto">
            <div class="auth-form-light text-left py-5 px-4 px-sm-5">
              <div class="brand-logo">
                <img src="/static/dashboard/images/logo.png" alt="logo">
              </div>
              <h4>Hello! let's get started</h4>
              <h6 class="fw-light">Please fill in the form to create an account.</h6>
              <form method="post" id="applyForm" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="container" style="max-width:600px;">
                  <h2 align="center" id='color'>Application Form</h2><br /><br />

                  <div id='color' style="padding-bottom: 20px;">
                    {% csrf_token %}
                    {{ user_form|crispy}}
                    {{ profile_form|crispy }}
                  </div>

                    <button  class='text-center btn btn-light' type="submit">Submit</button><br><br><br><br>
                  
                </div>
              </form>
              <h1>{{errorone}} <br> {{errortwo}}</h1>
            </div>
          </div>
        </div>
      </div>
      <!-- content-wrapper ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>
  <!-- container-scroller -->
  <!-- plugins:js -->
  <script src="/static/dashboard/vendors/js/vendor.bundle.base.js"></script>
  <!-- endinject -->
  <!-- Plugin js for this page -->
  <script src="/static/dashboard/vendors/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
  <!-- End plugin js for this page -->
  <!-- inject:js -->
  <script src="/static/dashboard/js/off-canvas.js"></script>
  <script src="/static/dashboard/js/hoverable-collapse.js"></script>
  <script src="/static/dashboard/js/template.js"></script>
  <script src="/static/dashboard/js/settings.js"></script>
  <script src="/static/dashboard/js/todolist.js"></script>
  <!-- endinject -->
</body>

</html>



templates/reg_sign_in_out/registrationo.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block head_block %}
<!-- <link rel="stylesheet" type="text/css" href="{% static 'index.css' %}"> -->
<link rel="stylesheet" type="text/css" href="/static/index.css">

{% endblock head_block %}

{% block body_block %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

 <body>
  <br /><br />
  
  <style>
    #color{
      color: darkgrey; !important
    }
  </style>


  <form method="post" id="applyForm" enctype="multipart/form-data">
    {% csrf_token %}
  <div class="container" style="max-width:600px;">
   <h2 align="center" id='color'>Application Form</h2><br /><br />
   <!-- <table id='color' class='col-lg-4'>
    {{user_form|crispy}}<br>
    {{profile_form|crispy}}
  </table> -->

  <div id='color'>
    {% csrf_token %}
    {{ user_form|crispy}}
    {{ profile_form|crispy }}
  
   <button class='text-center btn btn-light' type="submit">Submit</button><br><br><br><br>
  </div>
</div>
</form>
  Error:
 <h1>{{errorone}} <br> {{errortwo}}</h1>
 </body>
</html>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


<script>
$(document).ready(function(){

 load_json_data('state');

 function load_json_data(id, parent_id)
 {
  var html_code = '';
  $.getJSON("/static/data.json", function(data){

   html_code += '<option value="">Select '+id+'</option>';
   $.each(data, function(key, value){
    if(id == 'state')
    {
     if(value.parent_id == '0')
     {
      html_code += '<option value="'+value.id+'">'+value.name+'</option>';
     }
    }
    else
    {
     if(value.parent_id == parent_id)
     {
      html_code += '<option value="'+value.id+'">'+value.name+'</option>';
     }
    }
   });
   $('#'+id).html(html_code);
  });

 }

 $(document).on('change', '#state', function(){
  var state_id = $(this).val();
  if(state_id != '')
  {
   load_json_data('district', state_id);
  }
  else
  {
   $('#district').html('<option value="">Select district</option>');
   $('#subdistrict').html('<option value="">Select subdistrict</option>');
  }
 });
 $(document).on('change', '#district', function(){
  var district_id = $(this).val();
  if(district_id != '')
  {
   load_json_data('subdistrict', district_id);
  }
  else
  {
   $('#subdistrict').html('<option value="">Select subdistrict</option>');
  }
 });
});
</script>
{% endblock %}